/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baobomb_opencvdemo_opencvjnitest_OpenCVJNITest */

#ifndef _Included_com_baobomb_opencvdemo_opencvjnitest_OpenCVJNITest
#define _Included_com_baobomb_opencvdemo_opencvjnitest_OpenCVJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baobomb_opencvdemo_opencvjnitest_OpenCVJNITest
 * Method:    test
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baobomb_opencvdemo_opencvjnitest_OpenCVJNITest_test
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
